from sqlalchemy import Column, String, Float, DateTime, ForeignKey, JSON, Text, Integer
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
from app.models.base import Base
import uuid

def get_utc_now():
    return datetime.now(timezone.utc)

def generate_uuid():
    return str(uuid.uuid4())

class OptimizationStrategy(Base):
    """Registry of available optimization strategies (Green, Carbon, Economic)."""
    __tablename__ = "optimization_strategies"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    name = Column(String(100), nullable=False, unique=True)
    description = Column(String(255))
    created_at = Column(DateTime(timezone=True), default=get_utc_now)

class RecommendationRecord(Base):
    """Historical record of optimization recommendations generated by the engine."""
    __tablename__ = "optimization_recommendations"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    strategy_id = Column(String(36), ForeignKey("optimization_strategies.id"), nullable=False)
    generated_at = Column(DateTime(timezone=True), default=get_utc_now, nullable=False)
    
    # Impacts
    expected_savings = Column(Float, default=0.0)
    carbon_reduction = Column(Float, default=0.0)
    renewable_increase = Column(Float, default=0.0)
    confidence_score = Column(Float, nullable=False)
    
    # Payload of actual actions/setpoints recommended (JSON)
    recommendation_details = Column(JSON, nullable=False)
    
    # State tracking if the operator accepted it
    status = Column(String(50), default="pending") # pending, accepted, rejected
    
class ScenarioSimulation(Base):
    """User-triggered What-If scenarios."""
    __tablename__ = "optimization_scenarios"
    
    id = Column(String(36), primary_key=True, default=generate_uuid)
    name = Column(String(100), nullable=False)
    simulated_at = Column(DateTime(timezone=True), default=get_utc_now, nullable=False)
    
    # The overrides applied (e.g. +20% demand)
    overrides_json = Column(JSON, nullable=False)
    
    # The resulting best strategy
    recommended_strategy_id = Column(String(36), ForeignKey("optimization_strategies.id"), nullable=False)
    expected_savings = Column(Float, default=0.0)
    confidence_score = Column(Float, nullable=False)


class OptimizationConfig(Base):
    """Configuration settings for optimization algorithms and resource limits."""
    __tablename__ = "optimization_configs"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    name = Column(String(100), nullable=False)
    mode = Column(String(50), nullable=False, default="BALANCED") # BALANCED, ECONOMIC, GREEN, STABILITY
    solver_settings_json = Column(JSON, nullable=True) # max_iterations, tolerance, timeout
    resource_limits_json = Column(JSON, nullable=True) # cpu_cores, memory_mb
    constraints_json = Column(JSON, nullable=True) # enabled constraints list
    objectives_json = Column(JSON, nullable=True) # weights for objectives
    created_at = Column(DateTime(timezone=True), default=get_utc_now)


class OptimizationJob(Base):
    """Lifecycles of secure grid optimization task executions."""
    __tablename__ = "optimization_jobs"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    status = Column(String(20), default="PENDING", nullable=False) # PENDING, QUEUED, RUNNING, COMPLETED, FAILED, CANCELLED
    priority = Column(String(20), default="MEDIUM", nullable=False) # LOW, MEDIUM, HIGH, CRITICAL
    config_id = Column(String(36), ForeignKey("optimization_configs.id"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True) # Operator correlation context
    scheduled_at = Column(DateTime(timezone=True), default=get_utc_now, nullable=False)
    started_at = Column(DateTime(timezone=True), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    progress = Column(Float, default=0.0, nullable=False) # 0.0 to 100.0
    error_message = Column(String(255), nullable=True)

    config = relationship("OptimizationConfig")
    user = relationship("User")


class OptimizationExecutionHistory(Base):
    """Post-execution log metrics and result payloads from optimization runs."""
    __tablename__ = "optimization_execution_history"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    job_id = Column(String(36), ForeignKey("optimization_jobs.id"), nullable=False)
    execution_time_ms = Column(Float, default=0.0, nullable=False)
    objective_score = Column(Float, default=0.0)
    results_json = Column(JSON, nullable=True)
    metrics_json = Column(JSON, nullable=True)
    logs = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), default=get_utc_now)

    job = relationship("OptimizationJob")


class GridOptimizationResult(Base):
    """Detailed high-fidelity engineering optimization results for each sub-engine."""
    __tablename__ = "grid_optimization_results"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    job_id = Column(String(36), ForeignKey("optimization_jobs.id"), nullable=False)
    overall_score = Column(Float, default=0.0)
    load_balancing_json = Column(JSON, nullable=True)
    power_flow_json = Column(JSON, nullable=True)
    battery_schedules_json = Column(JSON, nullable=True)
    renewable_optimization_json = Column(JSON, nullable=True)
    peak_shaving_json = Column(JSON, nullable=True)
    demand_response_json = Column(JSON, nullable=True)
    reserve_margin_json = Column(JSON, nullable=True)
    stability_metrics_json = Column(JSON, nullable=True)
    ai_explanation = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), default=get_utc_now)

    job = relationship("OptimizationJob")


class FinancialCarbonResult(Base):
    """Detailed financial savings and carbon footprint optimization results."""
    __tablename__ = "financial_carbon_results"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    job_id = Column(String(36), ForeignKey("optimization_jobs.id"), nullable=False)
    market_price_profile_json = Column(JSON, nullable=True)
    cost_optimization_json = Column(JSON, nullable=True)
    carbon_optimization_json = Column(JSON, nullable=True)
    financial_reports_json = Column(JSON, nullable=True)
    ai_financial_explanation = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), default=get_utc_now)

    job = relationship("OptimizationJob")


class MultiObjectiveDecisionResult(Base):
    """Detailed multi-objective strategy, weights, trade-off and sensitivity evaluations."""
    __tablename__ = "multi_objective_decisions"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    job_id = Column(String(36), ForeignKey("optimization_jobs.id"), nullable=False)
    weights_json = Column(JSON, nullable=True)
    strategies_json = Column(JSON, nullable=True)
    trade_off_json = Column(JSON, nullable=True)
    sensitivity_analysis_json = Column(JSON, nullable=True)
    what_if_scenarios_json = Column(JSON, nullable=True)
    ai_recommendation_json = Column(JSON, nullable=True)
    created_at = Column(DateTime(timezone=True), default=get_utc_now)

    job = relationship("OptimizationJob")


class OptimizationAnalyticsSnapshot(Base):
    """Periodic KPI snapshots aggregating optimization performance over time."""
    __tablename__ = "optimization_analytics_snapshots"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    period = Column(String(20), nullable=False)  # DAILY, WEEKLY, MONTHLY
    period_start = Column(DateTime(timezone=True), nullable=False)
    period_end = Column(DateTime(timezone=True), nullable=False)

    # Aggregate KPIs
    total_jobs = Column(Integer, default=0)
    successful_jobs = Column(Integer, default=0)
    failed_jobs = Column(Integer, default=0)
    cancelled_jobs = Column(Integer, default=0)
    success_rate = Column(Float, default=0.0)
    avg_execution_time_ms = Column(Float, default=0.0)
    avg_objective_score = Column(Float, default=0.0)

    # Financial & Environmental KPIs
    avg_cost_savings_usd = Column(Float, default=0.0)
    avg_carbon_avoided_tons = Column(Float, default=0.0)
    avg_stability_score = Column(Float, default=0.0)
    avg_renewable_pct = Column(Float, default=0.0)
    avg_ai_confidence = Column(Float, default=0.0)

    # Extended metrics JSON
    metrics_json = Column(JSON, nullable=True)
    created_at = Column(DateTime(timezone=True), default=get_utc_now)


class OptimizationAuditEntry(Base):
    """Immutable audit log per optimization job for governance and compliance."""
    __tablename__ = "optimization_audit_entries"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    job_id = Column(String(36), ForeignKey("optimization_jobs.id"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    timestamp = Column(DateTime(timezone=True), default=get_utc_now, nullable=False)

    # Decision context
    config_mode = Column(String(50), nullable=True)
    objectives_json = Column(JSON, nullable=True)
    constraints_json = Column(JSON, nullable=True)
    strategy_selected = Column(String(100), nullable=True)
    alternative_strategies_json = Column(JSON, nullable=True)
    ai_recommendation_json = Column(JSON, nullable=True)
    confidence_score = Column(Float, default=0.0)

    # Execution context
    execution_time_ms = Column(Float, default=0.0)
    final_status = Column(String(20), nullable=True)
    objective_score = Column(Float, default=0.0)
    warnings_json = Column(JSON, nullable=True)
    errors_json = Column(JSON, nullable=True)

    job = relationship("OptimizationJob")
    user = relationship("User")


