"""Add AI models

Revision ID: 2c5e396ed921
Revises: a3ee64d3bd83
Create Date: 2026-07-25 19:33:01.838663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5e396ed921'
down_revision: Union[str, None] = 'a3ee64d3bd83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_decision_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('context_data_json', sa.JSON(), nullable=False),
    sa.Column('retrieved_rag_docs', sa.JSON(), nullable=True),
    sa.Column('raw_llm_response', sa.Text(), nullable=False),
    sa.Column('structured_recommendation', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operator_action', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_decision_logs')
    # ### end Alembic commands ###
