"""expand_training_replay_models

Revision ID: 510a046144e8
Revises: 888c2f956f4f
Create Date: 2026-07-25 22:13:22.598751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510a046144e8'
down_revision: Union[str, None] = '888c2f956f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    if 'trainee_analytics' not in tables:
        op.create_table('trainee_analytics',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('trainee_username', sa.String(length=100), nullable=False),
        sa.Column('training_progress', sa.Float(), nullable=True),
        sa.Column('average_score', sa.Float(), nullable=True),
        sa.Column('completion_rate', sa.Float(), nullable=True),
        sa.Column('average_response_time', sa.Float(), nullable=True),
        sa.Column('decision_accuracy', sa.Float(), nullable=True),
        sa.Column('weak_areas_json', sa.JSON(), nullable=True),
        sa.Column('improvement_trends_json', sa.JSON(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('trainee_username')
        )
        
    if 'replay_sessions' not in tables:
        op.create_table('replay_sessions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('simulation_id', sa.String(length=36), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('timeline_events_json', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['simulation_id'], ['simulation_runs.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        
    # Check columns for certifications
    cert_cols = [c['name'] for c in inspector.get_columns('certifications')]
    if 'session_id' not in cert_cols:
        op.add_column('certifications', sa.Column('session_id', sa.String(length=36), nullable=True))
        
    # Check columns for operator_assessments
    assess_cols = [c['name'] for c in inspector.get_columns('operator_assessments')]
    if 'metrics_json' not in assess_cols:
        op.add_column('operator_assessments', sa.Column('metrics_json', sa.JSON(), nullable=True))
    if 'ai_feedback' not in assess_cols:
        op.add_column('operator_assessments', sa.Column('ai_feedback', sa.Text(), nullable=True))
        
    # Check columns for training_sessions
    sess_cols = [c['name'] for c in inspector.get_columns('training_sessions')]
    if 'is_certification_mode' not in sess_cols:
        op.add_column('training_sessions', sa.Column('is_certification_mode', sa.Boolean(), nullable=False, server_default='0'))
    if 'team_id' not in sess_cols:
        op.add_column('training_sessions', sa.Column('team_id', sa.String(length=36), nullable=True))
    if 'saved_state_json' not in sess_cols:
        op.add_column('training_sessions', sa.Column('saved_state_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_sessions', 'saved_state_json')
    op.drop_column('training_sessions', 'team_id')
    op.drop_column('training_sessions', 'is_certification_mode')
    op.drop_column('operator_assessments', 'ai_feedback')
    op.drop_column('operator_assessments', 'metrics_json')
    op.drop_column('certifications', 'session_id')
    op.drop_table('replay_sessions')
    op.drop_table('trainee_analytics')
    # ### end Alembic commands ###

