"""add_optimization_foundation

Revision ID: 583b55641606
Revises: 510a046144e8
Create Date: 2026-07-25 22:29:57.441855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583b55641606'
down_revision: Union[str, None] = '510a046144e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('solver_settings_json', sa.JSON(), nullable=True),
    sa.Column('resource_limits_json', sa.JSON(), nullable=True),
    sa.Column('constraints_json', sa.JSON(), nullable=True),
    sa.Column('objectives_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('config_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['optimization_configs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_execution_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('objective_score', sa.Float(), nullable=True),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['optimization_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimization_execution_history')
    op.drop_table('optimization_jobs')
    op.drop_table('optimization_configs')
    # ### end Alembic commands ###
