"""Add ScenarioEvent

Revision ID: 790afcfb3283
Revises: 981df3cf3850
Create Date: 2026-07-25 19:53:05.378484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790afcfb3283'
down_revision: Union[str, None] = '981df3cf3850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('start_offset_mins', sa.Integer(), nullable=False),
    sa.Column('duration_mins', sa.Integer(), nullable=False),
    sa.Column('target_assets_json', sa.JSON(), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='PUBLISHED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_templates', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('scenario_events')
    # ### end Alembic commands ###
