"""Add training models

Revision ID: 888c2f956f4f
Revises: e4cb1bd942c5
Create Date: 2026-07-25 20:13:47.643221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888c2f956f4f'
down_revision: Union[str, None] = 'e4cb1bd942c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trainee_username', sa.String(length=100), nullable=False),
    sa.Column('certification_level', sa.String(length=50), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trainee_username', sa.String(length=100), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('training_session_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_score', sa.Float(), nullable=False),
    sa.Column('decision_score', sa.Float(), nullable=False),
    sa.Column('final_grade', sa.String(length=2), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operator_assessments')
    op.drop_table('training_sessions')
    op.drop_table('certifications')
    # ### end Alembic commands ###
