"""Add EngWeatherProfile

Revision ID: 967a375c82b6
Revises: f487f48adecf
Create Date: 2026-07-25 01:20:21.124041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967a375c82b6'
down_revision: Union[str, None] = 'f487f48adecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eng_weather_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('solar_irradiance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eng_weather_profiles_region_id'), 'eng_weather_profiles', ['region_id'], unique=False)
    op.create_index(op.f('ix_eng_weather_profiles_timestamp'), 'eng_weather_profiles', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eng_weather_profiles_timestamp'), table_name='eng_weather_profiles')
    op.drop_index(op.f('ix_eng_weather_profiles_region_id'), table_name='eng_weather_profiles')
    op.drop_table('eng_weather_profiles')
    # ### end Alembic commands ###
