"""Add scenario models

Revision ID: 981df3cf3850
Revises: 2c5e396ed921
Create Date: 2026-07-25 19:46:59.342650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981df3cf3850'
down_revision: Union[str, None] = '2c5e396ed921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_group_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('estimated_duration_mins', sa.Integer(), nullable=True),
    sa.Column('trigger_conditions_json', sa.JSON(), nullable=False),
    sa.Column('expected_outcomes_json', sa.JSON(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_system_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_templates_scenario_group_id'), 'scenario_templates', ['scenario_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_templates_scenario_group_id'))

    op.drop_table('scenario_templates')
    # ### end Alembic commands ###
