"""Add optimization models

Revision ID: a3ee64d3bd83
Revises: 4afeca059e86
Create Date: 2026-07-25 19:30:03.967586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ee64d3bd83'
down_revision: Union[str, None] = '4afeca059e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_strategies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('optimization_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_savings', sa.Float(), nullable=True),
    sa.Column('carbon_reduction', sa.Float(), nullable=True),
    sa.Column('renewable_increase', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('recommendation_details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['optimization_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('simulated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overrides_json', sa.JSON(), nullable=False),
    sa.Column('recommended_strategy_id', sa.String(length=36), nullable=False),
    sa.Column('expected_savings', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['recommended_strategy_id'], ['optimization_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('optimization_scenarios')
    op.drop_table('optimization_recommendations')
    op.drop_table('optimization_strategies')
    # ### end Alembic commands ###
