"""add_multi_objective_decisions_table

Revision ID: c585dd85af1a
Revises: 6b4a740aa34b
Create Date: 2026-07-25 22:52:17.701497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c585dd85af1a'
down_revision: Union[str, None] = '6b4a740aa34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multi_objective_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('weights_json', sa.JSON(), nullable=True),
    sa.Column('strategies_json', sa.JSON(), nullable=True),
    sa.Column('trade_off_json', sa.JSON(), nullable=True),
    sa.Column('sensitivity_analysis_json', sa.JSON(), nullable=True),
    sa.Column('what_if_scenarios_json', sa.JSON(), nullable=True),
    sa.Column('ai_recommendation_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['optimization_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multi_objective_decisions')
    # ### end Alembic commands ###
