"""Add integration tables

Revision ID: d49e0d445482
Revises: 967a375c82b6
Create Date: 2026-07-25 17:26:49.875258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49e0d445482'
down_revision: Union[str, None] = '967a375c82b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('internal_asset_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_mappings_external_id'), 'asset_mappings', ['external_id'], unique=False)
    op.create_index(op.f('ix_asset_mappings_provider_type'), 'asset_mappings', ['provider_type'], unique=False)
    op.create_table('integration_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('polling_interval', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('messages_received', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_configs_name'), 'integration_configs', ['name'], unique=True)
    op.create_index(op.f('ix_eng_assets_status'), 'eng_assets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eng_assets_status'), table_name='eng_assets')
    op.drop_index(op.f('ix_integration_configs_name'), table_name='integration_configs')
    op.drop_table('integration_configs')
    op.drop_index(op.f('ix_asset_mappings_provider_type'), table_name='asset_mappings')
    op.drop_index(op.f('ix_asset_mappings_external_id'), table_name='asset_mappings')
    op.drop_table('asset_mappings')
    # ### end Alembic commands ###
