"""Add phase 5.1 integration telemetry models

Revision ID: d4c8122cb721
Revises: e8f6f7489021
Create Date: 2026-07-25 18:37:51.246118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4c8122cb721'
down_revision: Union[str, None] = 'e8f6f7489021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('issue_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['integration_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry_timeseries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['integration_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_timeseries_asset_id'), 'telemetry_timeseries', ['asset_id'], unique=False)
    op.create_index(op.f('ix_telemetry_timeseries_metric_name'), 'telemetry_timeseries', ['metric_name'], unique=False)
    op.create_index(op.f('ix_telemetry_timeseries_timestamp'), 'telemetry_timeseries', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_telemetry_timeseries_timestamp'), table_name='telemetry_timeseries')
    op.drop_index(op.f('ix_telemetry_timeseries_metric_name'), table_name='telemetry_timeseries')
    op.drop_index(op.f('ix_telemetry_timeseries_asset_id'), table_name='telemetry_timeseries')
    op.drop_table('telemetry_timeseries')
    op.drop_table('data_quality_logs')
    # ### end Alembic commands ###
