"""Add analysis models

Revision ID: e4cb1bd942c5
Revises: d60f3b3eceb5
Create Date: 2026-07-25 20:06:18.451134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4cb1bd942c5'
down_revision: Union[str, None] = 'd60f3b3eceb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_analysis_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('simulation_id', sa.String(length=36), nullable=False),
    sa.Column('executive_summary_json', sa.JSON(), nullable=False),
    sa.Column('financial_impact_json', sa.JSON(), nullable=False),
    sa.Column('carbon_impact_json', sa.JSON(), nullable=False),
    sa.Column('grid_health_score', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    op.create_table('strategy_comparisons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('base_sim_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_sim_id', sa.String(length=36), nullable=False),
    sa.Column('winner_strategy', sa.String(length=100), nullable=True),
    sa.Column('kpi_diff_json', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_sim_id'], ['simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['candidate_sim_id'], ['simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_explainability_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.String(length=1000), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['simulation_analysis_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_explainability_traces')
    op.drop_table('strategy_comparisons')
    op.drop_table('simulation_analysis_reports')
    # ### end Alembic commands ###
