"""Add event tables

Revision ID: e8f6f7489021
Revises: d49e0d445482
Create Date: 2026-07-25 17:43:07.636342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f6f7489021'
down_revision: Union[str, None] = 'd49e0d445482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_engineering_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('measurement_type', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('secondary_threshold', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_engineering_rules_asset_type'), 'ops_engineering_rules', ['asset_type'], unique=False)
    op.create_index(op.f('ix_ops_engineering_rules_measurement_type'), 'ops_engineering_rules', ['measurement_type'], unique=False)
    op.create_index(op.f('ix_ops_engineering_rules_name'), 'ops_engineering_rules', ['name'], unique=False)
    op.create_table('ops_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_category', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_events_asset_id'), 'ops_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ops_events_event_category'), 'ops_events', ['event_category'], unique=False)
    op.create_index(op.f('ix_ops_events_event_type'), 'ops_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_ops_events_region'), 'ops_events', ['region'], unique=False)
    op.create_index(op.f('ix_ops_events_severity'), 'ops_events', ['severity'], unique=False)
    op.create_index(op.f('ix_ops_events_timestamp'), 'ops_events', ['timestamp'], unique=False)
    op.create_table('ops_incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_incidents_asset_id'), 'ops_incidents', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ops_incidents_priority'), 'ops_incidents', ['priority'], unique=False)
    op.create_index(op.f('ix_ops_incidents_region'), 'ops_incidents', ['region'], unique=False)
    op.create_index(op.f('ix_ops_incidents_severity'), 'ops_incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_ops_incidents_status'), 'ops_incidents', ['status'], unique=False)
    op.create_table('ops_alarms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alarm_type', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('trigger_event_id', sa.UUID(), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['ops_incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['ops_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_alarms_alarm_type'), 'ops_alarms', ['alarm_type'], unique=False)
    op.create_index(op.f('ix_ops_alarms_asset_id'), 'ops_alarms', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ops_alarms_region'), 'ops_alarms', ['region'], unique=False)
    op.create_index(op.f('ix_ops_alarms_severity'), 'ops_alarms', ['severity'], unique=False)
    op.create_index(op.f('ix_ops_alarms_status'), 'ops_alarms', ['status'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_index(op.f('ix_ops_alarms_status'), table_name='ops_alarms')
    op.drop_index(op.f('ix_ops_alarms_severity'), table_name='ops_alarms')
    op.drop_index(op.f('ix_ops_alarms_region'), table_name='ops_alarms')
    op.drop_index(op.f('ix_ops_alarms_asset_id'), table_name='ops_alarms')
    op.drop_index(op.f('ix_ops_alarms_alarm_type'), table_name='ops_alarms')
    op.drop_table('ops_alarms')
    op.drop_index(op.f('ix_ops_incidents_status'), table_name='ops_incidents')
    op.drop_index(op.f('ix_ops_incidents_severity'), table_name='ops_incidents')
    op.drop_index(op.f('ix_ops_incidents_region'), table_name='ops_incidents')
    op.drop_index(op.f('ix_ops_incidents_priority'), table_name='ops_incidents')
    op.drop_index(op.f('ix_ops_incidents_asset_id'), table_name='ops_incidents')
    op.drop_table('ops_incidents')
    op.drop_index(op.f('ix_ops_events_timestamp'), table_name='ops_events')
    op.drop_index(op.f('ix_ops_events_severity'), table_name='ops_events')
    op.drop_index(op.f('ix_ops_events_region'), table_name='ops_events')
    op.drop_index(op.f('ix_ops_events_event_type'), table_name='ops_events')
    op.drop_index(op.f('ix_ops_events_event_category'), table_name='ops_events')
    op.drop_index(op.f('ix_ops_events_asset_id'), table_name='ops_events')
    op.drop_table('ops_events')
    op.drop_index(op.f('ix_ops_engineering_rules_name'), table_name='ops_engineering_rules')
    op.drop_index(op.f('ix_ops_engineering_rules_measurement_type'), table_name='ops_engineering_rules')
    op.drop_index(op.f('ix_ops_engineering_rules_asset_type'), table_name='ops_engineering_rules')
    op.drop_table('ops_engineering_rules')
    # ### end Alembic commands ###
