"""Add engineering models for Phase 4.1

Revision ID: f487f48adecf
Revises: 
Create Date: 2026-07-25 00:57:49.967704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f487f48adecf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eng_demand_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('demand', sa.Float(), nullable=False),
    sa.Column('peak_demand', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eng_demand_profiles_region'), 'eng_demand_profiles', ['region'], unique=False)
    op.create_index(op.f('ix_eng_demand_profiles_timestamp'), 'eng_demand_profiles', ['timestamp'], unique=False)
    op.create_table('eng_regions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eng_regions_name'), 'eng_regions', ['name'], unique=False)
    op.create_table('eng_renewable_generation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('plant', sa.String(length=255), nullable=False),
    sa.Column('generation', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eng_renewable_generation_plant'), 'eng_renewable_generation', ['plant'], unique=False)
    op.create_index(op.f('ix_eng_renewable_generation_timestamp'), 'eng_renewable_generation', ['timestamp'], unique=False)
    op.create_index(op.f('ix_eng_renewable_generation_type'), 'eng_renewable_generation', ['type'], unique=False)
    op.create_table('eng_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['eng_regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eng_assets_asset_type'), 'eng_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_eng_assets_name'), 'eng_assets', ['name'], unique=False)
    op.create_table('eng_battery_storage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('state_of_charge', sa.Float(), nullable=True),
    sa.Column('charging_rate', sa.Float(), nullable=True),
    sa.Column('discharging_rate', sa.Float(), nullable=True),
    sa.Column('efficiency', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['eng_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eng_generators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('generator_type', sa.String(length=100), nullable=False),
    sa.Column('installed_capacity', sa.Float(), nullable=False),
    sa.Column('minimum_output', sa.Float(), nullable=True),
    sa.Column('maximum_output', sa.Float(), nullable=True),
    sa.Column('fuel_type', sa.String(length=100), nullable=True),
    sa.Column('operating_cost', sa.Float(), nullable=True),
    sa.Column('emission_factor', sa.Float(), nullable=True),
    sa.Column('operational_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['eng_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eng_transmission_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_substation', sa.String(length=255), nullable=False),
    sa.Column('destination_substation', sa.String(length=255), nullable=False),
    sa.Column('voltage_level', sa.Float(), nullable=True),
    sa.Column('line_length', sa.Float(), nullable=True),
    sa.Column('thermal_limit', sa.Float(), nullable=True),
    sa.Column('resistance', sa.Float(), nullable=True),
    sa.Column('reactance', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['eng_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eng_transmission_lines')
    op.drop_table('eng_generators')
    op.drop_table('eng_battery_storage')
    op.drop_index(op.f('ix_eng_assets_name'), table_name='eng_assets')
    op.drop_index(op.f('ix_eng_assets_asset_type'), table_name='eng_assets')
    op.drop_table('eng_assets')
    op.drop_index(op.f('ix_eng_renewable_generation_type'), table_name='eng_renewable_generation')
    op.drop_index(op.f('ix_eng_renewable_generation_timestamp'), table_name='eng_renewable_generation')
    op.drop_index(op.f('ix_eng_renewable_generation_plant'), table_name='eng_renewable_generation')
    op.drop_table('eng_renewable_generation')
    op.drop_index(op.f('ix_eng_regions_name'), table_name='eng_regions')
    op.drop_table('eng_regions')
    op.drop_index(op.f('ix_eng_demand_profiles_timestamp'), table_name='eng_demand_profiles')
    op.drop_index(op.f('ix_eng_demand_profiles_region'), table_name='eng_demand_profiles')
    op.drop_table('eng_demand_profiles')
    # ### end Alembic commands ###
